### ISSUE TITLE
Add compound ThrowableStorage so exceptions are also logged to Data/Logs/Exceptions

### ISSUE THREAD

**Issue by nlx-lars** [netlogix/Netlogix.Sentry#2]
Currently, the default storage class is set to the `SentryThrowableStorage`, which disables the default `FileStorage` of Flow:
```yaml
Neos:
  Flow:
    log:
      throwables:
        storageClass: Netlogix\Sentry\ThrowableStorage\SentryThrowableStorage
```

This could be solved by adding some sort of compound ThrowableStorage, that internally uses both, the `FileStorage` and `SentryThrowableStorage`.

Also while we're at it, it might make sense to rename the `SentryThrowableStorage` to just `SentryStorage`.
