### ISSUE TITLE
Add option to specify Environment

### ISSUE THREAD

**Issue by nlx-lars** [netlogix/Netlogix.Sentry#3]
By default, sentry searches for the environment variable `SENTRY_ENVIRONMENT`. For projects without environment variables, it should be possible to set the environment through the settings.

Similar to the `Settings.Release.yaml`:
```yaml
Netlogix:
  Sentry:
    environment:
      setting: '%env:SENTRY_ENVIRONMENT%'
```

We could then introduce a `FlowSettings` Provider for the Environment.

Since the default setting is `%env:SENTRY_ENVIRONMENT%`, this will also work for projects with environment variables.
